### ISSUE TITLE
Jekyll "build" command does not work on Ruby 2.5 on Docker

### ISSUE THREAD

**Issue by eduardo-matos** [JugglerX/jekyll-serif-theme#1]
This is the output for ruby 2.5.3 on Docker:

![image](https://user-images.githubusercontent.com/483681/54167631-7a7fad80-4449-11e9-967f-82432358adc5.png)

This is the Dockerfile:

```dockerfile
FROM ruby:2.5.3

COPY . /app

WORKDIR /app

RUN ruby -v && \
    gem install bundler && \
    bundle install && \
    jekyll build -d public/
```

**Comment by JugglerX** [comment]
Maybe try `bundle exec jekyll build`

I don't really know much about Docker, sorry. Does it work when just using
your systems ruby?
--------------------------------------------

*Email:* rob@jugglerdigital.com
*Web:* www.jugglerdigital.com
*Phone (AUS):* +61 473 189 717
*Phone (USA):* +1 415 996 6632* (inactive)*
*Skype:* jugglerdigital

**Comment by eduardo-matos** [comment]
> Maybe try `bundle exec jekyll build

It outputs the same error :confused: 

> Does it work when just using your systems ruby?

Yes.

--
I've tried to run on Docker using the same version I have on my machine, but it still doesn't work.  
I need it to work on Docker because I'm trying to deploy on Gitlab, and its CI uses Docker under the hood.

**Comment by JugglerX** [comment]
Ok well if it works without being inside Docker, I'd say the issue is coming from your Docker setup. I'm sorry I don't even know where to begin debugging your Docker implementation.
